[molecules]
input_files: acetic_acid_a.xyz,
             acetic_acid_b.xyz,
             acetic_acid_c.xyz,
             acetic_acid_d.xyz
    
[vdw.surface.options]
vdw_scale_factors : 1.4, 1.6, 1.8, 2.0
vdw_point_density : 1.0
esp               : acetic_acid_a_esp.dat,
                    acetic_acid_b_esp.dat,
                    acetic_acid_c_esp.dat,
                    acetic_acid_d_esp.dat

grid              : acetic_acid_a_grid.dat,
                    acetic_acid_b_grid.dat,
                    acetic_acid_c_grid.dat,
                    acetic_acid_d_grid.dat

vdw_radii_set     : legacy
vdw_radii         : None

[hyperbolic.restraint.options]
weight            : 1.0
restraint         : True
resp_a            : 0.001
resp_b            : 0.1
ihfree            : True
toler             : 1e-5
max_it            : 50 

[constraints]
# fixed charges: atom_number (in xyz file) = partial_charge,
constraint_charge : 5 =  0.77601234,
                    6 = -0.63151916,
                    7 =  0.43386458,
                    8 = -0.5782523

#groups of equivalent atoms -> group_n = atom_number list,
equivalent_groups : group_1 = 2 3 4

[qm.options]
method_esp    : None
basis_esp     : None

formal_charge : 0
multiplicity  : 1